"""fligth db

Revision ID: 076c7dbd537e
Revises: d377679c3f0f
Create Date: 2025-05-05 23:09:05.111087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076c7dbd537e'
down_revision = 'd377679c3f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_name', sa.String(length=50), nullable=False),
    sa.Column('plane_name', sa.String(length=50), nullable=False),
    sa.Column('flight_origin', sa.String(length=50), nullable=False),
    sa.Column('flight_departure', sa.String(length=50), nullable=False),
    sa.Column('flight_date', sa.DateTime(), nullable=False),
    sa.Column('flight_price', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
