"""flight and user many and hotel

Revision ID: ee4721390c0b
Revises: ece98ce76281
Create Date: 2025-05-08 22:15:30.873999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4721390c0b'
down_revision = 'ece98ce76281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('hotel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_name', sa.String(length=50), nullable=False),
    sa.Column('hotel_rooms', sa.Enum('Room_1', 'Room_2', 'Room_3', 'Room_4', 'Suite', name='room'), nullable=False),
    sa.Column('hotel_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel')
    # ### end Alembic commands ###
